name: build

on:
  schedule:
    - cron: "00 3 * * 6"
  push:
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU-action
      uses: docker/setup-qemu-action@v1

    - name: Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        itags: ronivay/xen-orchestra:latest
